[[headers]]
  for = "/src/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/src/*"
  to = "/.netlify/functions/assets/icons/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
